MoviesTime.Web/Areas/TheaterManager/Controllers/GenreLangController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using MoviesTime.BusinessLayer.Interface;
using MoviesTime.Contract.DbModels;
using MoviesTime.Contract.ViewModels;

namespace MoviesTime.Web.Areas.TheaterManager.Controllers;

[Area("TheaterManager")]
public class GenreLangController : Controller
{
    private readonly ISharedService _sharedService;
    private readonly ITheaterManager _theaterManager;

    public GenreLangController(ITheaterManager theaterManager, ISharedService sharedService)
    {
        _sharedService = sharedService;
        _theaterManager = theaterManager;
    }

    //Public methods
    public IActionResult ManageGenreLanguages(ManageGenreLanguagesViewModel viewModel)
    {
        viewModel.lstGenres = GetGenresList();
        viewModel.lstLanguages = GetLanguagesList();
        return View(viewModel);
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult CreateGenre(ManageGenreLanguagesViewModel viewModel) 
    {
        if (!ModelState.IsValid)
        {
            Console.WriteLine("|| model state invalid ||");
            return View("ManageGenreLanguages", viewModel);
        }
        //if (!viewModel.genre.GenreName.IsNullOrEmpty()
        //    && viewModel.genre.ID == 0)  
        //    _theaterManager.CreateGenre(viewModel.genre);
        return RedirectToAction("ManageGenreLanguages");
    }

    public IActionResult CreateLanguage(ManageGenreLanguagesViewModel viewModel)
    {
        if (!ModelState.IsValid)
        {
            Console.WriteLine("|| model state invalid ||");
            return View("ManageGenreLanguages", viewModel);
        }
        //if (!viewModel.language.Language.IsNullOrEmpty() 
        //    && viewModel.language.LanguageID == 0)
        //    _theaterManager.CreateLanguage(viewModel.language);
        return RedirectToAction("ManageGenreLanguages");
    }

    public IActionResult EditGenre(int id)
    {
        ManageGenreLanguagesViewModel viewModel = new ManageGenreLanguagesViewModel()
        {
            genre = _theaterManager.GetGenreDetailsByID(id),
            lstGenres = GetGenresList(),
            lstLanguages = GetLanguagesList(),
            IsGenreEditMode = true
        };
        return View("ManageGenreLanguages", viewModel);
    }

    public IActionResult EditLanguage(int id)
    {
        ManageGenreLanguagesViewModel viewModel = new ManageGenreLanguagesViewModel()
        {
            language = _theaterManager.GetLanguageDetailsByID(id),
            lstGenres = GetGenresList(),
            lstLanguages = GetLanguagesList(),
            IsLanguageEditMode = true
        };
        return View("ManageGenreLanguages", viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeleteGenre(int id)
    {
        // Delete the customer logic

        // Set the success message in ViewData
        //ViewData["DeleteSuccess"] = "Customer deleted successfully.";

        // Redirect back to the view
        return RedirectToAction("Index");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeleteLanguage(int id)
    {
        // Delete the customer logic

        // Set the success message in ViewData
        //ViewData["DeleteSuccess"] = "Customer deleted successfully.";

        // Redirect back to the view
        return RedirectToAction("Index");
    }
    // Private Methods
    private List<Genres> GetGenresList()
    {
        return _sharedService.GetGenresList();
    }
    private List<Languages> GetLanguagesList()
    {
        return _sharedService.GetLanguagesList();
    }
}

MoviesTime.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
   <link rel="stylesheet" href="~/css/BootswatchTheme.css"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.5.0/dist/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="Customer" asp-controller="Home" asp-action="index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="TheaterManager" asp-controller="ManageTheaters" asp-action="ManageTheaters">Manage Theaters</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="TheaterManager" asp-controller="ManageTheaterScreens" asp-action="ManageTheaterScreens">Manage Theater Screens</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="TheaterManager" asp-controller="GenreLang" asp-action="ManageGenreLanguages">Manage Genre/Language</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="TheaterManager" asp-controller="ManageMovies" asp-action="ManageMovies">Manage Movies</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link" href="#">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>*@
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        @RenderBody()
    </div>
    <footer>
      @* <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        *@
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    </footer>
</body>
</html>

MoviesTime.Web/Views/Shared/_ValidationsPartialScript.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@